// 扩展数据模块 - 增加更多不锈钢牌号和技术参数
const ExtendedData = {
    // 新增GB标准牌号
    gbExtended: {
        "12Cr18Ni9": {
            standard: "GB/T 20878",
            uns: "S30200",
            series: "300系列",
            type: "austenitic",
            family: "chromium-nickel",
            yield_strength: 205,
            tensile_strength: 520,
            elongation: 40,
            hardness: "HB 187",
            cr: "17.0-19.0",
            ni: "8.0-10.0",
            c: "≤0.15",
            si: "≤1.00",
            mn: "≤2.00",
            p: "≤0.045",
            s: "≤0.030",
            applications: "餐具、装饰品、建筑装饰",
            description: "奥氏体不锈钢，具有良好的耐腐蚀性和加工性能"
        },
        "06Cr18Ni11Ti": {
            standard: "GB/T 20878",
            uns: "S32100",
            series: "300系列",
            type: "austenitic",
            family: "chromium-nickel-titanium",
            yield_strength: 205,
            tensile_strength: 520,
            elongation: 40,
            hardness: "HB 187",
            cr: "17.0-19.0",
            ni: "9.0-12.0",
            ti: "≥5×C",
            c: "≤0.08",
            si: "≤1.00",
            mn: "≤2.00",
            p: "≤0.045",
            s: "≤0.030",
            applications: "化工设备、热交换器、锅炉",
            description: "含钛奥氏体不锈钢，具有优异的抗晶间腐蚀性能"
        },
        "06Cr17Ni12Mo2": {
            standard: "GB/T 20878",
            uns: "S31600",
            series: "300系列",
            type: "austenitic",
            family: "chromium-nickel-molybdenum",
            yield_strength: 205,
            tensile_strength: 520,
            elongation: 40,
            hardness: "HB 187",
            cr: "16.0-18.0",
            ni: "10.0-14.0",
            mo: "2.0-3.0",
            c: "≤0.08",
            si: "≤1.00",
            mn: "≤2.00",
            p: "≤0.045",
            s: "≤0.030",
            applications: "海洋环境、化工设备、医疗器械",
            description: "含钼奥氏体不锈钢，具有优异的耐腐蚀性能"
        },
        "022Cr17Ni12Mo2": {
            standard: "GB/T 20878",
            uns: "S31603",
            series: "300系列",
            type: "austenitic",
            family: "chromium-nickel-molybdenum",
            yield_strength: 170,
            tensile_strength: 485,
            elongation: 40,
            hardness: "HB 217",
            cr: "16.0-18.0",
            ni: "10.0-14.0",
            mo: "2.0-3.0",
            c: "≤0.03",
            si: "≤1.00",
            mn: "≤2.00",
            p: "≤0.045",
            s: "≤0.030",
            applications: "核工业、化工设备、海洋工程",
            description: "超低碳含钼奥氏体不锈钢，具有优异的耐腐蚀性能"
        },
        "10Cr17": {
            standard: "GB/T 20878",
            uns: "S43000",
            series: "400系列",
            type: "ferritic",
            family: "chromium",
            yield_strength: 205,
            tensile_strength: 450,
            elongation: 22,
            hardness: "HB 183",
            cr: "16.0-18.0",
            c: "≤0.12",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "建筑装饰、汽车装饰、家用电器",
            description: "铁素体不锈钢，具有良好的耐腐蚀性和经济性"
        },
        "12Cr13": {
            standard: "GB/T 20878",
            uns: "S41000",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 520,
            elongation: 20,
            hardness: "HB 201",
            cr: "11.5-13.5",
            c: "≤0.15",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "刀具、阀门、泵零件",
            description: "马氏体不锈钢，具有较高的强度和硬度"
        },
        "20Cr13": {
            standard: "GB/T 20878",
            uns: "S42000",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 540,
            elongation: 20,
            hardness: "HB 235",
            cr: "12.0-14.0",
            c: "0.16-0.25",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "医疗器械、刀具、阀门",
            description: "马氏体不锈钢，具有较高的强度和耐腐蚀性"
        }
    },

    // 新增ASTM标准牌号
    astmExtended: {
        "201": {
            standard: "ASTM A240/A240M",
            uns: "S20100",
            series: "200系列",
            type: "austenitic",
            family: "chromium-nickel-manganese",
            yield_strength: 275,
            tensile_strength: 655,
            elongation: 40,
            hardness: "HB 201",
            cr: "16.0-18.0",
            ni: "3.5-5.5",
            mn: "5.5-7.5",
            n: "0.25",
            c: "≤0.15",
            si: "≤1.00",
            p: "≤0.060",
            s: "≤0.030",
            applications: "建筑装饰、汽车装饰、家用电器",
            description: "节镍奥氏体不锈钢，具有良好的经济性"
        },
        "202": {
            standard: "ASTM A240/A240M",
            uns: "S20200",
            series: "200系列",
            type: "austenitic",
            family: "chromium-nickel-manganese",
            yield_strength: 275,
            tensile_strength: 655,
            elongation: 40,
            hardness: "HB 201",
            cr: "17.0-19.0",
            ni: "4.0-6.0",
            mn: "7.5-10.0",
            n: "0.25",
            c: "≤0.15",
            si: "≤1.00",
            p: "≤0.060",
            s: "≤0.030",
            applications: "建筑装饰、汽车装饰、家用电器",
            description: "节镍奥氏体不锈钢，具有良好的经济性"
        },
        "301": {
            standard: "ASTM A240/A240M",
            uns: "S30100",
            series: "300系列",
            type: "austenitic",
            family: "chromium-nickel",
            yield_strength: 205,
            tensile_strength: 520,
            elongation: 40,
            hardness: "HB 201",
            cr: "16.0-18.0",
            ni: "6.0-8.0",
            c: "≤0.15",
            si: "≤1.00",
            mn: "≤2.00",
            p: "≤0.045",
            s: "≤0.030",
            applications: "建筑装饰、汽车装饰、家用电器",
            description: "奥氏体不锈钢，具有良好的加工性能"
        },
        "310": {
            standard: "ASTM A240/A240M",
            uns: "S31000",
            series: "300系列",
            type: "austenitic",
            family: "chromium-nickel",
            yield_strength: 205,
            tensile_strength: 520,
            elongation: 40,
            hardness: "HB 201",
            cr: "24.0-26.0",
            ni: "19.0-22.0",
            c: "≤0.25",
            si: "≤1.50",
            mn: "≤2.00",
            p: "≤0.045",
            s: "≤0.030",
            applications: "高温设备、热处理设备、化工设备",
            description: "高铬镍奥氏体不锈钢，具有优异的高温性能"
        },
        "310S": {
            standard: "ASTM A240/A240M",
            uns: "S31008",
            series: "300系列",
            type: "austenitic",
            family: "chromium-nickel",
            yield_strength: 205,
            tensile_strength: 520,
            elongation: 40,
            hardness: "HB 201",
            cr: "24.0-26.0",
            ni: "19.0-22.0",
            c: "≤0.08",
            si: "≤1.50",
            mn: "≤2.00",
            p: "≤0.045",
            s: "≤0.030",
            applications: "高温设备、热处理设备、化工设备",
            description: "超低碳高铬镍奥氏体不锈钢，具有优异的高温性能"
        },
        "410": {
            standard: "ASTM A240/A240M",
            uns: "S41000",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 520,
            elongation: 20,
            hardness: "HB 201",
            cr: "11.5-13.5",
            c: "≤0.15",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "刀具、阀门、泵零件",
            description: "马氏体不锈钢，具有较高的强度和硬度"
        },
        "420": {
            standard: "ASTM A240/A240M",
            uns: "S42000",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 540,
            elongation: 20,
            hardness: "HB 235",
            cr: "12.0-14.0",
            c: "0.15-0.40",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "医疗器械、刀具、阀门",
            description: "马氏体不锈钢，具有较高的强度和耐腐蚀性"
        },
        "430": {
            standard: "ASTM A240/A240M",
            uns: "S43000",
            series: "400系列",
            type: "ferritic",
            family: "chromium",
            yield_strength: 205,
            tensile_strength: 450,
            elongation: 22,
            hardness: "HB 183",
            cr: "16.0-18.0",
            c: "≤0.12",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "建筑装饰、汽车装饰、家用电器",
            description: "铁素体不锈钢，具有良好的耐腐蚀性和经济性"
        },
        "440A": {
            standard: "ASTM A240/A240M",
            uns: "S44002",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 415,
            tensile_strength: 725,
            elongation: 20,
            hardness: "HB 269",
            cr: "16.0-18.0",
            c: "0.60-0.75",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "刀具、轴承、阀门",
            description: "高碳马氏体不锈钢，具有极高的硬度和耐磨性"
        },
        "440B": {
            standard: "ASTM A240/A240M",
            uns: "S44003",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 415,
            tensile_strength: 760,
            elongation: 20,
            hardness: "HB 285",
            cr: "16.0-18.0",
            c: "0.75-0.95",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "刀具、轴承、阀门",
            description: "高碳马氏体不锈钢，具有极高的硬度和耐磨性"
        },
        "440C": {
            standard: "ASTM A240/A240M",
            uns: "S44004",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 415,
            tensile_strength: 760,
            elongation: 20,
            hardness: "HB 285",
            cr: "16.0-18.0",
            c: "0.95-1.20",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "刀具、轴承、阀门",
            description: "超高碳马氏体不锈钢，具有极高的硬度和耐磨性"
        },
        // 新增沉淀硬化不锈钢
        "17-4PH": {
            standard: "ASTM A240/A240M",
            uns: "S17400",
            series: "沉淀硬化系列",
            type: "precipitation-hardening",
            family: "chromium-nickel-copper",
            yield_strength: 1170,
            tensile_strength: 1310,
            elongation: 10,
            hardness: "HB 363",
            cr: "15.0-17.5",
            ni: "3.0-5.0",
            cu: "3.0-5.0",
            nb: "0.15-0.45",
            c: "≤0.07",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "航空航天、化工设备、精密仪器",
            description: "沉淀硬化不锈钢，具有高强度和高耐腐蚀性"
        },
        "15-5PH": {
            standard: "ASTM A240/A240M",
            uns: "S15500",
            series: "沉淀硬化系列",
            type: "precipitation-hardening",
            family: "chromium-nickel-copper",
            yield_strength: 1035,
            tensile_strength: 1170,
            elongation: 12,
            hardness: "HB 331",
            cr: "14.0-15.5",
            ni: "3.5-5.5",
            cu: "2.5-4.5",
            nb: "0.07-0.13",
            c: "≤0.07",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "航空航天、化工设备、精密仪器",
            description: "沉淀硬化不锈钢，具有高强度和高耐腐蚀性"
        },
        "13-8PH": {
            standard: "ASTM A240/A240M",
            uns: "S13800",
            series: "沉淀硬化系列",
            type: "precipitation-hardening",
            family: "chromium-nickel-aluminum",
            yield_strength: 1035,
            tensile_strength: 1170,
            elongation: 12,
            hardness: "HB 331",
            cr: "12.25-13.25",
            ni: "7.5-8.5",
            al: "0.90-1.35",
            c: "≤0.05",
            si: "≤0.20",
            mn: "≤0.20",
            p: "≤0.025",
            s: "≤0.025",
            applications: "航空航天、核工业、精密仪器",
            description: "沉淀硬化不锈钢，具有高强度和高耐腐蚀性"
        }
    },

    // 新增EN标准牌号
    enExtended: {
        "1.4000": {
            standard: "EN 10088-1",
            uns: "S41000",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 520,
            elongation: 20,
            hardness: "HB 201",
            cr: "11.5-13.5",
            c: "≤0.15",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "刀具、阀门、泵零件",
            description: "马氏体不锈钢，具有较高的强度和硬度"
        },
        "1.4001": {
            standard: "EN 10088-1",
            uns: "S41003",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 520,
            elongation: 20,
            hardness: "HB 201",
            cr: "11.5-13.5",
            c: "≤0.15",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "刀具、阀门、泵零件",
            description: "马氏体不锈钢，具有较高的强度和硬度"
        },
        "1.4002": {
            standard: "EN 10088-1",
            uns: "S42000",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 540,
            elongation: 20,
            hardness: "HB 235",
            cr: "12.0-14.0",
            c: "0.16-0.25",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "医疗器械、刀具、阀门",
            description: "马氏体不锈钢，具有较高的强度和耐腐蚀性"
        },
        "1.4003": {
            standard: "EN 10088-1",
            uns: "S42003",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 345,
            tensile_strength: 540,
            elongation: 20,
            hardness: "HB 235",
            cr: "12.0-14.0",
            c: "0.16-0.25",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "医疗器械、刀具、阀门",
            description: "马氏体不锈钢，具有较高的强度和耐腐蚀性"
        },
        "1.4005": {
            standard: "EN 10088-1",
            uns: "S40300",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 275,
            tensile_strength: 485,
            elongation: 20,
            hardness: "HB 183",
            cr: "11.5-13.5",
            c: "≤0.08",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "蒸汽轮机叶片、阀门",
            description: "低碳马氏体不锈钢，具有良好的耐腐蚀性"
        },
        "1.4006": {
            standard: "EN 10088-1",
            uns: "S41008",
            series: "400系列",
            type: "martensitic",
            family: "chromium",
            yield_strength: 275,
            tensile_strength: 485,
            elongation: 20,
            hardness: "HB 183",
            cr: "11.5-13.5",
            c: "≤0.08",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "蒸汽轮机叶片、阀门",
            description: "低碳马氏体不锈钢，具有良好的耐腐蚀性"
        },
        "1.4016": {
            standard: "EN 10088-1",
            uns: "S43000",
            series: "400系列",
            type: "ferritic",
            family: "chromium",
            yield_strength: 205,
            tensile_strength: 450,
            elongation: 22,
            hardness: "HB 183",
            cr: "16.0-18.0",
            c: "≤0.08",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            applications: "建筑装饰、汽车装饰、家用电器",
            description: "铁素体不锈钢，具有良好的耐腐蚀性和经济性"
        },
        "1.4510": {
            standard: "EN 10088-1",
            uns: "S43900",
            series: "400系列",
            type: "ferritic",
            family: "chromium",
            yield_strength: 205,
            tensile_strength: 450,
            elongation: 22,
            hardness: "HB 183",
            cr: "17.0-19.0",
            c: "≤0.03",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            ti: "0.20-1.00",
            applications: "汽车排气系统、建筑装饰",
            description: "超低碳铁素体不锈钢，具有优异的耐腐蚀性"
        },
        "1.4511": {
            standard: "EN 10088-1",
            uns: "S43900",
            series: "400系列",
            type: "ferritic",
            family: "chromium",
            yield_strength: 205,
            tensile_strength: 450,
            elongation: 22,
            hardness: "HB 183",
            cr: "17.0-19.0",
            c: "≤0.03",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            ti: "0.20-1.00",
            applications: "汽车排气系统、建筑装饰",
            description: "超低碳铁素体不锈钢，具有优异的耐腐蚀性"
        },
        "1.4512": {
            standard: "EN 10088-1",
            uns: "S43900",
            series: "400系列",
            type: "ferritic",
            family: "chromium",
            yield_strength: 205,
            tensile_strength: 450,
            elongation: 22,
            hardness: "HB 183",
            cr: "17.0-19.0",
            c: "≤0.03",
            si: "≤1.00",
            mn: "≤1.00",
            p: "≤0.040",
            s: "≤0.030",
            ti: "0.20-1.00",
            applications: "汽车排气系统、建筑装饰",
            description: "超低碳铁素体不锈钢，具有优异的耐腐蚀性"
        }
    },

    // 新增镍基合金
    nickelAlloys: {
        "Inconel 600": {
            standard: "ASTM B168",
            uns: "N06600",
            series: "镍基合金",
            type: "nickel-chromium",
            family: "nickel-based",
            yield_strength: 240,
            tensile_strength: 550,
            elongation: 30,
            hardness: "HB 150",
            ni: "≥72.0",
            cr: "14.0-17.0",
            fe: "6.0-10.0",
            c: "≤0.15",
            si: "≤0.50",
            mn: "≤1.00",
            p: "≤0.015",
            s: "≤0.015",
            applications: "高温设备、化工设备、核工业",
            description: "镍铬铁合金，具有优异的高温强度和耐腐蚀性"
        },
        "Inconel 601": {
            standard: "ASTM B168",
            uns: "N06601",
            series: "镍基合金",
            type: "nickel-chromium-aluminum",
            family: "nickel-based",
            yield_strength: 240,
            tensile_strength: 550,
            elongation: 30,
            hardness: "HB 150",
            ni: "58.0-63.0",
            cr: "21.0-25.0",
            fe: "余量",
            al: "1.0-1.7",
            c: "≤0.10",
            si: "≤0.50",
            mn: "≤1.00",
            p: "≤0.020",
            s: "≤0.015",
            applications: "高温设备、热处理设备、化工设备",
            description: "镍铬铝铁合金，具有优异的高温抗氧化性"
        },
        "Inconel 625": {
            standard: "ASTM B443",
            uns: "N06625",
            series: "镍基合金",
            type: "nickel-chromium-molybdenum",
            family: "nickel-based",
            yield_strength: 345,
            tensile_strength: 690,
            elongation: 30,
            hardness: "HB 200",
            ni: "≥58.0",
            cr: "20.0-23.0",
            mo: "8.0-10.0",
            fe: "≤5.0",
            nb: "3.15-4.15",
            c: "≤0.10",
            si: "≤0.50",
            mn: "≤0.50",
            p: "≤0.015",
            s: "≤0.015",
            applications: "海洋工程、化工设备、航空航天",
            description: "镍铬钼合金，具有优异的耐腐蚀性和高强度"
        },
        "Inconel 718": {
            standard: "ASTM B637",
            uns: "N07718",
            series: "镍基合金",
            type: "nickel-chromium-iron",
            family: "nickel-based",
            yield_strength: 1035,
            tensile_strength: 1240,
            elongation: 12,
            hardness: "HB 331",
            ni: "50.0-55.0",
            cr: "17.0-21.0",
            fe: "余量",
            nb: "4.75-5.50",
            mo: "2.8-3.3",
            ti: "0.65-1.15",
            al: "0.20-0.80",
            c: "≤0.08",
            si: "≤0.35",
            mn: "≤0.35",
            p: "≤0.015",
            s: "≤0.015",
            applications: "航空航天、燃气轮机、核工业",
            description: "沉淀硬化镍基合金，具有极高的强度和耐腐蚀性"
        },
        "Hastelloy C276": {
            standard: "ASTM B575",
            uns: "N10276",
            series: "镍基合金",
            type: "nickel-chromium-molybdenum",
            family: "nickel-based",
            yield_strength: 345,
            tensile_strength: 690,
            elongation: 40,
            hardness: "HB 200",
            ni: "≥52.0",
            cr: "14.5-16.5",
            mo: "15.0-17.0",
            fe: "4.0-7.0",
            w: "3.0-4.5",
            co: "≤2.5",
            c: "≤0.02",
            si: "≤0.08",
            mn: "≤1.00",
            p: "≤0.025",
            s: "≤0.010",
            applications: "化工设备、海洋工程、核工业",
            description: "镍铬钼钨合金，具有优异的耐腐蚀性"
        },
        "Monel 400": {
            standard: "ASTM B127",
            uns: "N04400",
            series: "镍基合金",
            type: "nickel-copper",
            family: "nickel-based",
            yield_strength: 240,
            tensile_strength: 550,
            elongation: 40,
            hardness: "HB 150",
            ni: "63.0-70.0",
            cu: "余量",
            fe: "≤2.5",
            c: "≤0.30",
            si: "≤0.50",
            mn: "≤2.00",
            p: "≤0.025",
            s: "≤0.024",
            applications: "海洋工程、化工设备、船舶制造",
            description: "镍铜合金，具有优异的耐海水腐蚀性"
        },
        "Monel K500": {
            standard: "ASTM B865",
            uns: "N05500",
            series: "镍基合金",
            type: "nickel-copper-aluminum",
            family: "nickel-based",
            yield_strength: 550,
            tensile_strength: 760,
            elongation: 20,
            hardness: "HB 250",
            ni: "63.0-70.0",
            cu: "余量",
            al: "2.3-3.15",
            ti: "0.35-0.85",
            fe: "≤2.0",
            c: "≤0.25",
            si: "≤0.50",
            mn: "≤1.50",
            p: "≤0.025",
            s: "≤0.010",
            applications: "海洋工程、化工设备、精密仪器",
            description: "沉淀硬化镍铜合金，具有高强度和高耐腐蚀性"
        }
    },

    // 应用扩展数据
    applyExtendedData() {
        if (typeof DB !== 'undefined') {
            // 合并GB数据
            Object.assign(DB.gb, this.gbExtended);
            
            // 合并ASTM数据
            Object.assign(DB.astm, this.astmExtended);
            
            // 合并EN数据
            Object.assign(DB.en, this.enExtended);
            
            // 添加镍基合金数据
            if (!DB.nickel) {
                DB.nickel = {};
            }
            Object.assign(DB.nickel, this.nickelAlloys);
            
            console.log('扩展数据已加载:', {
                gb: Object.keys(this.gbExtended).length,
                astm: Object.keys(this.astmExtended).length,
                en: Object.keys(this.enExtended).length,
                nickel: Object.keys(this.nickelAlloys).length
            });
        }
    },

    // 获取数据统计
    getDataStats() {
        if (typeof DB !== 'undefined') {
            return {
                total: Object.keys(DB.gb).length + Object.keys(DB.astm).length + Object.keys(DB.en).length + Object.keys(DB.nickel || {}).length,
                gb: Object.keys(DB.gb).length,
                astm: Object.keys(DB.astm).length,
                en: Object.keys(DB.en).length,
                nickel: Object.keys(DB.nickel || {}).length,
                types: {
                    austenitic: 0,
                    ferritic: 0,
                    martensitic: 0,
                    duplex: 0,
                    "precipitation-hardening": 0,
                    "nickel-chromium": 0,
                    "nickel-copper": 0
                }
            };
        }
        return null;
    }
};

// 初始化扩展数据
document.addEventListener('DOMContentLoaded', () => {
    if (typeof ExtendedData !== 'undefined') {
        ExtendedData.applyExtendedData();
    }
}); 